modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "valkyrien_ship_schematics"
version = "${version}"
displayName = "Valkyrien Ship Schematics"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.valkyrien_ship_schematics]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrien_ship_schematics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrien_ship_schematics]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
