plugins {
    id 'org.jetbrains.kotlin.jvm'
}
architectury {
    common("forge", "fabric")
}
repositories {
    maven {
        name = "Valkyrien Skies Internal"
        url = 'https://maven.valkyrienskies.org'
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$project.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$project.architectury_api_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    api 'org.joml:joml-primitives:1.10.0'
    api 'org.joml:joml:1.10.4'

    compileOnly("org.valkyrienskies.core:api:${project.vs_core_version}")
    compileOnly("org.valkyrienskies.core:api-game:${project.vs_core_version}")
    compileOnly("org.valkyrienskies.core:util:${project.vs_core_version}")
    compileOnly("org.valkyrienskies.core:impl:${project.vs_core_version}")
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}